### ISSUE TITLE
Travis CI sometimes fails: ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by william-r-s** [oughtinc/ergo#134]
First build fails https://travis-ci.org/github/oughtinc/ergo/builds/677419499

Second build succeeds after spurious change https://github.com/oughtinc/ergo/runs/603096647

Also see https://travis-ci.org/github/oughtinc/ergo/builds/675513509

`[EnvCommandError]
Command ['/home/travis/virtualenv/python3.6.9/bin/pip', 'install', '--no-deps', 'pandas==1.0.3'] errored with the following return code 2, and output: 
Collecting pandas==1.0.3
  Downloading https://files.pythonhosted.org/packages/bb/71/8f53bdbcbc67c912b888b40def255767e475402e9df64050019149b1a943/pandas-1.0.3-cp36-cp36m-manylinux1_x86_64.whl (10.0MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/opt/python/3.6.9/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/opt/python/3.6.9/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/opt/python/3.6.9/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/python/3.6.9/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/python/3.6.9/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/opt/python/3.6.9/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/download.py", line 886, in unpack_url
    progress_bar=progress_bar
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/download.py", line 746, in unpack_http_url
    progress_bar)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/download.py", line 954, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/download.py", line 683, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/download.py", line 651, in written_chunks
    for chunk in chunks:
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 156, in iter
    for x in it:
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_internal/download.py", line 640, in resp_read
    decode_content=False):
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/opt/python/3.6.9/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/travis/virtualenv/python3.6.9/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
The command "poetry install" failed and exited with 1 during .`

**Comment by stuhlmueller** [comment]
https://travis-ci.com/github/oughtinc/ergo/builds/161897757
